python plotTurnOn.py --numerator demo/histoDir/recoHT_nominalHT410_monitoring --denominator demo/histoDir/recoHT_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoHT_nominalHT250_monitoring --denominator demo/histoDir/recoHT_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoMjj_nominalHT250_monitoring --denominator demo/histoDir/recoMjj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoMjj_nominalHT410_monitoring --denominator demo/histoDir/recoMjj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoDeltaEtajj_nominalHT250_monitoring --denominator demo/histoDir/recoDeltaEtajj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoDeltaEtajj_nominalHT410_monitoring --denominator demo/histoDir/recoDeltaEtajj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoMjjWide_nominalHT250_monitoring --denominator demo/histoDir/recoMjjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoMjjWide_nominalHT410_monitoring --denominator demo/histoDir/recoMjjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoDeltaEtajjWide_nominalHT250_monitoring --denominator demo/histoDir/recoDeltaEtajjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/recoDeltaEtajjWide_nominalHT410_monitoring --denominator demo/histoDir/recoDeltaEtajjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfHT_nominalHT410_monitoring --denominator demo/histoDir/pfHT_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfHT_nominalHT250_monitoring --denominator demo/histoDir/pfHT_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfMjj_nominalHT250_monitoring --denominator demo/histoDir/pfMjj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfMjj_nominalHT410_monitoring --denominator demo/histoDir/pfMjj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfDeltaEtajj_nominalHT250_monitoring --denominator demo/histoDir/pfDeltaEtajj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfDeltaEtajj_nominalHT410_monitoring --denominator demo/histoDir/pfDeltaEtajj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfMjjWide_nominalHT250_monitoring --denominator demo/histoDir/pfMjjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfMjjWide_nominalHT410_monitoring --denominator demo/histoDir/pfMjjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfDeltaEtajjWide_nominalHT250_monitoring --denominator demo/histoDir/pfDeltaEtajjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/pfDeltaEtajjWide_nominalHT410_monitoring --denominator demo/histoDir/pfDeltaEtajjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloHT_nominalHT410_monitoring --denominator demo/histoDir/caloHT_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloHT_nominalHT250_monitoring --denominator demo/histoDir/caloHT_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloMjj_nominalHT250_monitoring --denominator demo/histoDir/caloMjj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloMjj_nominalHT410_monitoring --denominator demo/histoDir/caloMjj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloDeltaEtajj_nominalHT250_monitoring --denominator demo/histoDir/caloDeltaEtajj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloDeltaEtajj_nominalHT410_monitoring --denominator demo/histoDir/caloDeltaEtajj_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloMjjWide_nominalHT250_monitoring --denominator demo/histoDir/caloMjjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloMjjWide_nominalHT410_monitoring --denominator demo/histoDir/caloMjjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloDeltaEtajjWide_nominalHT250_monitoring --denominator demo/histoDir/caloDeltaEtajjWide_monitoring -i AnalysisOutput_v8.root --lumi 536
python plotTurnOn.py --numerator demo/histoDir/caloDeltaEtajjWide_nominalHT410_monitoring --denominator demo/histoDir/caloDeltaEtajjWide_monitoring -i AnalysisOutput_v8.root --lumi 536